### ISSUE TITLE
somehow it does not work

### ISSUE THREAD

**Issue by georgesuba** [kimili/No-DB-URL-Shortener#3]
Hi,

thanks for providing this code, but I cannot get this work in subfolder..  I followed your readme file. im on debian classic virtualmin setup.. when I do generate link I get following:

`{"originalURL":"https:\/\/github.com\/kimili\/No-DB-URL-Shortener","shortURL":"http:\/\/mydomain.uk\/xyeqP","baseURL":"mydomain.uk","hash":"xyeqP"}`

but shortener is in mydomain.uk/l/  - any thoughts?

**Comment by solvaholic** [comment]
I edited ./lib/URLShortener/URLShortener.php, changing
$hash = substr($url, 1);
to
$hash = substr($url, 12);

I access my No-DB-URL-Shortener on a shared server like :
http://server/~usernam/us/xyeqP

If your URL shortener is in mydomain.uk/l/ then try :
$hash = substr($url, 3);

(To avoid seeing cached results, test in a new incognito browser window)
